/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background":               "#111318",
        "surface":                  "#111318",
        "surface-dim":              "#111318",
        "surface-container-lowest": "#0c0e13",
        "surface-container-low":    "#1a1b21",
        "surface-container":        "#1e1f25",
        "surface-container-high":   "#282a2f",
        "surface-container-highest":"#33353a",
        "surface-bright":           "#37393f",
        "surface-variant":          "#33353a",
        "outline-variant":          "#3d4a43",
        "outline":                  "#86948c",
        "on-surface-variant":       "#bccac1",
        "on-background":            "#e2e2e9",
        "on-surface":               "#e2e2e9",
        "primary":                  "#aaffd8",
        "primary-container":        "#6ee7b7",
        "primary-fixed":            "#80f9c8",
        "primary-fixed-dim":        "#62dcad",
        "on-primary":               "#003827",
        "on-primary-container":     "#006649",
        "on-primary-fixed":         "#002115",
        "inverse-primary":          "#006c4e",
        "secondary":                "#bdc2ff",
        "secondary-container":      "#2f3aa3",
        "secondary-fixed":          "#e0e0ff",
        "on-secondary":             "#131e8c",
        "on-secondary-container":   "#a8afff",
        "tertiary":                 "#ffecca",
        "tertiary-container":       "#ffca52",
        "tertiary-fixed":           "#ffdf9f",
        "tertiary-fixed-dim":       "#f9bd22",
        "on-tertiary":              "#402d00",
        "on-tertiary-container":    "#735500",
        "error":                    "#ffb4ab",
        "error-container":          "#93000a",
        "on-error":                 "#690005",
        "on-error-container":       "#ffdad6",
        "inverse-surface":          "#e2e2e9",
        "inverse-on-surface":       "#2e3036",
        "surface-tint":             "#62dcad",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body:     ["Manrope", "sans-serif"],
        label:    ["Manrope", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg:      "0.5rem",
        xl:      "0.75rem",
        "2xl":   "1rem",
        "3xl":   "1.5rem",
        full:    "9999px",
      },
    },
  },
  plugins: [],
};